Repository webpack-contrib/copy-webpack-plugin, pull requests merged in 2018-03, with the labels that each got.

#234 fix(index): `tapable` deprecation warnings (`webpack >= v4.0.0`)
  src/index.js
Labels: semver: Patch, status: Approved, type: Bug

#152 chore(package): update `loader-utils` v0.2.15...1.1.0
  package-lock.json
  package.json
  src/writeFile.js
Labels: semver: Patch, status: Approved, type: Chore

#235 feat(processPattern): add support for `{RegExp)` matches (`pattern.test`)
  README.md
  src/processPattern.js
  src/writeFile.js
  tests/index.js
Labels: pr_action: Review, priority: 5 (nice to have), semver: Minor, status: Pending, type: Feature

#239 perf(index): switch to `md4` for content hashing
  src/writeFile.js
Labels: semver: Patch, status: Approved, type: Perf

#238 fix(package): update `cacache` v10.0.1...10.0.4 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#242 docs(README): clarify `{Promise}` usage (`pattern.transform`) (#160)
  README.md
Labels: semver: Patch, status: Approved, type: Documentation
